[build]
publish = "."
command = "echo 'Build terminé'"

# ✅ Dossier des fonctions = racine
[functions]
directory = "."

# Variables d'environnement
[build.environment]
NODE_ENV = "production"

# ✅ Redirection pour la fonction (PRIORITÉ ABSOLUE)
[[redirects]]
from = "/.netlify/functions/env-vars"
to = "/env-vars.js"
status = 200
force = true

# Autres redirections
[[redirects]]
from = "/*.js"
to = "/:splat.js"
status = 200

[[redirects]]
from = "/*.css"  
to = "/:splat.css"
status = 200

[[redirects]]
from = "/*.html"
to = "/:splat.html"
status = 200

# SPA fallback EN DERNIER
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers CORS pour fonctions
[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"
