toml[build]
publish = "."
command = "echo 'Build CRM Pro terminé'"

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

# Variables d'environnement
[build.environment]
NODE_ENV = "production"

# Redirection SPA CORRIGÉE
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
# ❌ SUPPRIMÉ : conditions = {Role = ["admin", "user"]}

# Headers de sécurité
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co;"

# Cache pour fichiers statiques
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"
